import Head from 'next/head'
import HeroSection from "@/sections/welcome/HeroSection";
import UserSection from "@/sections/welcome/UserSection";
import HowItWorks from "@/sections/welcome/HowItWorks";
import Navbar from "@/components/Navbar";

export default function Home() {
    return (
        <div className>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>
            <HeroSection/>
            <UserSection/>
            <HowItWorks/>

        </div>
    )
}
