import Head from 'next/head';
import Navbar from '@/components/Navbar';
import HeroSection from '@/sections/welcome/HeroSection';
import UserSection from '@/sections/welcome/UserSection';
import HowItWorks from '@/sections/welcome/HowItWorks';
import MakeMoneySection from '@/sections/welcome/MakeMoneySection';
import FeaturesSection from '@/sections/welcome/FeaturesSection';
import InvestorsReviewSection from '@/sections/welcome/InvestorsReviewSection';
import InvestmentCalculatorSection from '@/sections/welcome/InvestmentCalculatorSection';
import PropertiesSection from '@/sections/welcome/PropertiesSection';
import RewardsSection from '@/sections/welcome/RewardsSection';
import BestAssetSection from '@/sections/welcome/BestAssetSection';
import ReadyToGetSection from '@/sections/welcome/ReadyToGetSection';

export default function Home() {
  return (
    <div className>
      <Head>
        <title>BNBShares</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="">
          <HeroSection />
          <UserSection />
          <HowItWorks />
          <MakeMoneySection />
          <FeaturesSection />
          <InvestorsReviewSection />
          <InvestmentCalculatorSection />
          <PropertiesSection />
          <RewardsSection />
          <BestAssetSection />
          <ReadyToGetSection />
      </div>
    </div>
  );
}
